
import java.util.ArrayList;
import java.util.Date;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Admin
 */
public class loginATM extends javax.swing.JFrame {

    /**
     * Creates new form loginATM
     */
    public loginATM() {
        initComponents();
        setResizable(false);
        setTitle("ATM");
        this.setLocationRelativeTo(null);
        HiloHora h = new HiloHora(jl_hora);
        Thread proceso1 = new Thread(h);
        proceso1.start();
        inhabilitarCampos();
        a.cargarBinario();
   //cb_cajeros = a.cargarBinario();

        b.cargarBinario();
        for (Usuarios usi : b.getUsuario()) {
            usuarios.add(usi);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jd_opciones = new javax.swing.JDialog();
        bt_crearUsuario = new javax.swing.JButton();
        bt_addATM = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        fondi = new javax.swing.JLabel();
        jd_usuarios = new javax.swing.JDialog();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        tf_segundoNombre = new javax.swing.JTextField();
        tf_primerApellido = new javax.swing.JTextField();
        tf_segundoApellido = new javax.swing.JTextField();
        tf_contraseña = new javax.swing.JTextField();
        tf_añoNacimiento = new javax.swing.JTextField();
        tf_afiliacion = new javax.swing.JTextField();
        tf_primerNombre = new javax.swing.JTextField();
        cb_usuarios = new javax.swing.JComboBox<>();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        tf_id = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        tf_userr = new javax.swing.JTextField();
        fond = new javax.swing.JLabel();
        jd_ATM = new javax.swing.JDialog();
        jd_OpcionesCliente = new javax.swing.JDialog();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jd_crearATM = new javax.swing.JDialog();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        tf_year = new javax.swing.JTextField();
        tf_ubicacion = new javax.swing.JTextField();
        tf_time = new javax.swing.JTextField();
        tf_id2 = new javax.swing.JTextField();
        tf_cantidad1 = new javax.swing.JTextField();
        jButton12 = new javax.swing.JButton();
        fon = new javax.swing.JLabel();
        jd_retirarDinero = new javax.swing.JDialog();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel16 = new javax.swing.JLabel();
        jl_hora = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        bt_Ingresar = new javax.swing.JButton();
        bt_exit = new javax.swing.JButton();
        tf_user = new javax.swing.JTextField();
        tf_password = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        cb_cajeros = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();

        jd_opciones.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bt_crearUsuario.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        bt_crearUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/atm_1.png"))); // NOI18N
        bt_crearUsuario.setText("Usuarios");
        bt_crearUsuario.setContentAreaFilled(false);
        bt_crearUsuario.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        bt_crearUsuario.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        bt_crearUsuario.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/atm (1)_1.png"))); // NOI18N
        bt_crearUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_crearUsuarioMouseClicked(evt);
            }
        });
        jd_opciones.getContentPane().add(bt_crearUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 190, 130));

        bt_addATM.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        bt_addATM.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/atm (2)_1.png"))); // NOI18N
        bt_addATM.setText("ATM");
        bt_addATM.setContentAreaFilled(false);
        bt_addATM.setHideActionText(true);
        bt_addATM.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        bt_addATM.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        bt_addATM.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/atm (3)_1.png"))); // NOI18N
        bt_addATM.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_addATMMouseClicked(evt);
            }
        });
        jd_opciones.getContentPane().add(bt_addATM, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, 130, 100));

        jButton1.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/return (4).png"))); // NOI18N
        jButton1.setText("Regresar");
        jButton1.setContentAreaFilled(false);
        jButton1.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        jButton1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/return (5).png"))); // NOI18N
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jd_opciones.getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 20, 150, 100));

        fondi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fila.jpg"))); // NOI18N
        jd_opciones.getContentPane().add(fondi, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 590, 340));

        jd_usuarios.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel5.setText("Registrate con tus datos correctos");
        jd_usuarios.getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, -1, -1));

        jLabel4.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel4.setText("ID Usuario");
        jd_usuarios.getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, -1, -1));

        jLabel6.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel6.setText("Segundo Nombre");
        jd_usuarios.getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 310, -1, -1));

        jLabel7.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel7.setText("Primer Apellido");
        jd_usuarios.getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 360, -1, -1));

        jLabel8.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel8.setText("Segundo Apellido");
        jd_usuarios.getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 420, -1, -1));

        jLabel9.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel9.setText("Contraseña");
        jd_usuarios.getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 480, -1, 20));

        jLabel10.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel10.setText("Año de nacimiento");
        jd_usuarios.getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 530, -1, -1));

        jLabel11.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel11.setText("Año de afiliación");
        jd_usuarios.getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 590, -1, -1));
        jd_usuarios.getContentPane().add(tf_segundoNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 300, 150, -1));
        jd_usuarios.getContentPane().add(tf_primerApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 360, 150, -1));
        jd_usuarios.getContentPane().add(tf_segundoApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 410, 150, -1));
        jd_usuarios.getContentPane().add(tf_contraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 470, 150, -1));
        jd_usuarios.getContentPane().add(tf_añoNacimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 530, 150, -1));
        jd_usuarios.getContentPane().add(tf_afiliacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 590, 160, -1));
        jd_usuarios.getContentPane().add(tf_primerNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 240, 150, -1));

        cb_usuarios.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        cb_usuarios.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "*Usuarios*", "Cliente", "Mantenimiento" }));
        jd_usuarios.getContentPane().add(cb_usuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 700, 110, 30));

        jButton3.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/atm (2).png"))); // NOI18N
        jButton3.setText("Registrar Usuario");
        jButton3.setContentAreaFilled(false);
        jButton3.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        jButton3.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/atm (3).png"))); // NOI18N
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });
        jd_usuarios.getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 710, 200, 100));

        jButton4.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/return (4).png"))); // NOI18N
        jButton4.setText("Regresar");
        jButton4.setContentAreaFilled(false);
        jButton4.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        jButton4.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        jButton4.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/return (5).png"))); // NOI18N
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });
        jd_usuarios.getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 710, 140, 100));

        tf_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_idActionPerformed(evt);
            }
        });
        jd_usuarios.getContentPane().add(tf_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 140, 150, -1));

        jLabel12.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel12.setText("Primer Nombre");
        jd_usuarios.getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, -1, -1));

        jLabel13.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel13.setText("Nombre de usuario");
        jd_usuarios.getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, -1, -1));
        jd_usuarios.getContentPane().add(tf_userr, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 190, 150, -1));

        fond.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/manATM.jpg"))); // NOI18N
        jd_usuarios.getContentPane().add(fond, new org.netbeans.lib.awtextra.AbsoluteConstraints(-120, 0, 690, 820));

        jd_ATM.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jd_OpcionesCliente.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton5.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jButton5.setText("Retirar/Ingresar Dinero");
        jd_OpcionesCliente.getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, -1, -1));

        jButton6.setText("jButton6");
        jd_OpcionesCliente.getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 70, -1, -1));

        jButton7.setText("jButton7");
        jd_OpcionesCliente.getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 70, -1, -1));

        jButton8.setText("jButton8");
        jd_OpcionesCliente.getContentPane().add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, -1, -1));

        jButton9.setText("jButton9");
        jd_OpcionesCliente.getContentPane().add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 220, -1, -1));

        jButton10.setText("jButton10");
        jd_OpcionesCliente.getContentPane().add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 220, -1, -1));

        jButton11.setText("jButton11");
        jd_OpcionesCliente.getContentPane().add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 420, -1, -1));
        jd_OpcionesCliente.getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 860, 440));

        jd_crearATM.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel17.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel17.setText("Ubicacion");
        jd_crearATM.getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 230, -1, -1));

        jLabel18.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel18.setText("Tiempo");
        jd_crearATM.getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 190, -1, -1));

        jLabel19.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel19.setText("Año");
        jd_crearATM.getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 280, -1, -1));

        jLabel21.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel21.setText("Cantidad");
        jd_crearATM.getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 110, -1, -1));

        jLabel22.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel22.setText("ID");
        jd_crearATM.getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 150, -1, -1));
        jd_crearATM.getContentPane().add(tf_year, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 280, 120, -1));
        jd_crearATM.getContentPane().add(tf_ubicacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 240, 120, -1));
        jd_crearATM.getContentPane().add(tf_time, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 200, 120, -1));
        jd_crearATM.getContentPane().add(tf_id2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 150, 120, -1));
        jd_crearATM.getContentPane().add(tf_cantidad1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 110, 120, -1));

        jButton12.setText("Crear ATM");
        jButton12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton12MouseClicked(evt);
            }
        });
        jd_crearATM.getContentPane().add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 350, 160, 40));

        fon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/mantCajero.jpg"))); // NOI18N
        jd_crearATM.getContentPane().add(fon, new org.netbeans.lib.awtextra.AbsoluteConstraints(-90, -20, 900, 480));

        jd_retirarDinero.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jd_retirarDinero.getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 40, -1, -1));
        jd_retirarDinero.getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 640));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jl_hora.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jl_hora.setText("00:00:00");
        getContentPane().add(jl_hora, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 650, 180, 30));

        jLabel2.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Usuario");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 170, 70, -1));

        jLabel3.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Contraseña");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 170, 110, -1));

        bt_Ingresar.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        bt_Ingresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/atm (2).png"))); // NOI18N
        bt_Ingresar.setText("Ingresar");
        bt_Ingresar.setContentAreaFilled(false);
        bt_Ingresar.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        bt_Ingresar.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        bt_Ingresar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/atm (3).png"))); // NOI18N
        getContentPane().add(bt_Ingresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 230, 160, 90));

        bt_exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/exit (2).png"))); // NOI18N
        bt_exit.setContentAreaFilled(false);
        bt_exit.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        bt_exit.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        bt_exit.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/exit (3).png"))); // NOI18N
        bt_exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_exitMouseClicked(evt);
            }
        });
        getContentPane().add(bt_exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 460, 110, 90));

        tf_user.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        tf_user.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(tf_user, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 200, 150, 30));

        tf_password.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        tf_password.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(tf_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 200, 150, 30));

        jLabel1.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Crear cuenta");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 490, 120, 30));

        getContentPane().add(cb_cajeros, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, 190, 40));

        jLabel15.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        jLabel15.setText("Antes de ingresar seleccione un ATM, por favor.");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, -1, -1));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cajero.jpg"))); // NOI18N
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 990, 680));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_exitMouseClicked
        System.exit(0);
    }//GEN-LAST:event_bt_exitMouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked

        jd_opciones.pack();
        jd_opciones.setModal(true);
        jd_opciones.setLocationRelativeTo(this);
        jd_opciones.setVisible(true);
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        jd_opciones.dispose();
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        jd_usuarios.dispose();
        jd_opciones.pack();
        jd_opciones.setModal(true);
        jd_opciones.setLocationRelativeTo(this);
        jd_opciones.setVisible(true);
    }//GEN-LAST:event_jButton4MouseClicked

    private void bt_crearUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_crearUsuarioMouseClicked
        jd_opciones.dispose();
        jd_usuarios.pack();
        jd_usuarios.setModal(true);
        jd_usuarios.setLocationRelativeTo(this);
        jd_usuarios.setVisible(true);
    }//GEN-LAST:event_bt_crearUsuarioMouseClicked

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        int id2;
        String nombre1, nombre2, apellido1, apellido2, contraseña, usuario, nacimiento, afiliacion, idd;
        int cuenta, saldo;

        nombre1 = tf_primerNombre.getText();
        nombre2 = tf_segundoNombre.getText();
        apellido1 = tf_primerApellido.getText();
        apellido2 = tf_segundoApellido.getText();
        usuario = tf_userr.getText();
        contraseña = tf_contraseña.getText();
        nacimiento = tf_añoNacimiento.getText();
        afiliacion = tf_afiliacion.getText();
        idd = tf_id.getText();
        int id = Integer.parseInt(idd);
        if (cb_usuarios.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(this, " Opcion incorrecta");
        } else if (cb_usuarios.getSelectedIndex() == 1) {

            usuarios.add(new usuarioCliente(id, 0, nombre1, nombre2, apellido1, apellido2, contraseña, nacimiento, afiliacion, usuario));
            JOptionPane.showMessageDialog(this, " Ha sido registrado como ofertador exitosamente");

            Usuarios l = new usuarioCliente(id, 0, nombre1, nombre2, apellido1, apellido2, contraseña, nacimiento, afiliacion, usuario);

            usuarios.add(l);
            b.cargarBinario();
            b.agregarOfertador(l);
            b.escribirBinarios();

        } else {

        }


    }//GEN-LAST:event_jButton3MouseClicked

    private void tf_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_idActionPerformed

    private void jButton12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton12MouseClicked

        cant = tf_cantidad1.getText();
        idd = tf_id2.getText();
        tiempo = tf_time.getText();
        ubicacion = tf_ubicacion.getText();
        year = tf_year.getText();

        int cantidad = Integer.parseInt(cant);
        int id = Integer.parseInt(idd);
        atms.add(new ATM(cantidad, xx, id, tiempo, ubicacion, year));

        ATM k = new ATM(cantidad, xx, id, tiempo, ubicacion, year);
        atms.add(k);
        a.cargarBinario();
        a.agregarATM(k);
        a.escribirBinarios();
        DefaultComboBoxModel st = (DefaultComboBoxModel) cb_cajeros.getModel();
        st.addElement(k);
        cb_cajeros.setModel(st);
        JOptionPane.showMessageDialog(this, "ATM agreado exitosamente");

    }//GEN-LAST:event_jButton12MouseClicked

    private void bt_addATMMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_addATMMouseClicked
        jd_opciones.dispose();
        jd_crearATM.pack();
        jd_crearATM.setModal(true);
        jd_crearATM.setLocationRelativeTo(this);
        jd_crearATM.setVisible(true);
    }//GEN-LAST:event_bt_addATMMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(loginATM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(loginATM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(loginATM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(loginATM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new loginATM().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_Ingresar;
    private javax.swing.JButton bt_addATM;
    private javax.swing.JButton bt_crearUsuario;
    private javax.swing.JButton bt_exit;
    private javax.swing.JComboBox<String> cb_cajeros;
    private javax.swing.JComboBox<String> cb_usuarios;
    private javax.swing.JLabel fon;
    private javax.swing.JLabel fond;
    private javax.swing.JLabel fondi;
    private javax.swing.JLabel fondo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JDialog jd_ATM;
    private javax.swing.JDialog jd_OpcionesCliente;
    private javax.swing.JDialog jd_crearATM;
    private javax.swing.JDialog jd_opciones;
    private javax.swing.JDialog jd_retirarDinero;
    private javax.swing.JDialog jd_usuarios;
    private javax.swing.JLabel jl_hora;
    private javax.swing.JTextField tf_afiliacion;
    private javax.swing.JTextField tf_añoNacimiento;
    private javax.swing.JTextField tf_cantidad1;
    private javax.swing.JTextField tf_contraseña;
    private javax.swing.JTextField tf_id;
    private javax.swing.JTextField tf_id2;
    private javax.swing.JPasswordField tf_password;
    private javax.swing.JTextField tf_primerApellido;
    private javax.swing.JTextField tf_primerNombre;
    private javax.swing.JTextField tf_segundoApellido;
    private javax.swing.JTextField tf_segundoNombre;
    private javax.swing.JTextField tf_time;
    private javax.swing.JTextField tf_ubicacion;
    private javax.swing.JTextField tf_user;
    private javax.swing.JTextField tf_userr;
    private javax.swing.JTextField tf_year;
    // End of variables declaration//GEN-END:variables
ArrayList<Usuarios> usuarios = new ArrayList();
    ArrayList<ATM> atms = new ArrayList();

    Binarios b = new Binarios(usuarios);
    adminATM a = new adminATM(atms);
    String cant, idd, tiempo, ubicacion, year;
    LogSistema xx = new LogSistema("", "", new Date());

    public void inhabilitarCampos() {
        tf_user.setEnabled(false);
        tf_password.setEnabled(false);
        bt_Ingresar.setEnabled(false);
    }



}
